require 'haml-rails'
require 'jquery-rails'
require 'kaminari'
require 'opener/client'

require_relative 'review_browser/engine'
require_relative 'review_browser/related_opinions_finder'
require_relative 'review_browser/analyzer'
require_relative 'review_browser/kaf_to_review_parser'
require_relative 'review_browser/review_importer'
require_relative 'review_browser/version'
